// This file is @generated by prost-build.
/// AppointmentStatusDoc - discriminated union for appointment states
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppointmentStatusDoc {
    #[prost(oneof = "appointment_status_doc::Status", tags = "1, 2, 3, 4, 5, 6")]
    pub status: ::core::option::Option<appointment_status_doc::Status>,
}
/// Nested message and enum types in `AppointmentStatusDoc`.
pub mod appointment_status_doc {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Status {
        #[prost(message, tag = "1")]
        Pending(super::Pending),
        #[prost(message, tag = "2")]
        Confirmed(super::Confirmed),
        #[prost(message, tag = "3")]
        Cancelled(super::Cancelled),
        #[prost(message, tag = "4")]
        Completed(super::Completed),
        #[prost(message, tag = "5")]
        NoShow(super::NoShow),
        #[prost(message, tag = "6")]
        Rescheduled(super::Rescheduled),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Pending {
    #[prost(int64, tag = "1")]
    pub created_at: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Confirmed {
    #[prost(int64, tag = "1")]
    pub confirmed_at: i64,
    #[prost(int32, tag = "2")]
    pub payment_module_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cancelled {
    #[prost(string, tag = "1")]
    pub cancel_code: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub cancelled_at: i64,
    /// "patient", "doctor", "system"
    #[prost(string, tag = "3")]
    pub cancelled_by: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Completed {
    #[prost(int64, tag = "1")]
    pub completed_at: i64,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NoShow {
    #[prost(int64, tag = "1")]
    pub no_show_at: i64,
    /// "patient", "doctor"
    #[prost(string, tag = "2")]
    pub no_show_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rescheduled {
    #[prost(int64, tag = "1")]
    pub rescheduled_at: i64,
    #[prost(string, tag = "2")]
    pub new_booking_id: ::prost::alloc::string::String,
    /// "patient", "doctor"
    #[prost(string, tag = "3")]
    pub rescheduled_by: ::prost::alloc::string::String,
}
