// This file is @generated by prost-build.
/// OnBoardingStatus - discriminated union with variant-specific data
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnBoardingStatus {
    #[prost(oneof = "on_boarding_status::Status", tags = "1, 2, 3, 4, 5, 6")]
    pub status: ::core::option::Option<on_boarding_status::Status>,
}
/// Nested message and enum types in `OnBoardingStatus`.
pub mod on_boarding_status {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Status {
        #[prost(message, tag = "1")]
        Draft(super::Draft),
        #[prost(message, tag = "2")]
        PendingApproval(super::PendingApproval),
        #[prost(message, tag = "3")]
        CancelledByUser(super::CancelledByUser),
        #[prost(message, tag = "4")]
        Approved(super::Approved),
        #[prost(message, tag = "5")]
        Rejected(super::Rejected),
        #[prost(message, tag = "6")]
        Deactivated(super::Deactivated),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Draft {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PendingApproval {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CancelledByUser {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Approved {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rejected {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deactivated {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
/// Name structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Name {
    #[prost(string, tag = "1")]
    pub firstname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub lastname: ::prost::alloc::string::String,
}
/// Address structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub address_detail: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sub_district: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub district: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub province: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub postal_code: ::prost::alloc::string::String,
}
/// Work place structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkPlace {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectedWorkPlace {
    #[prost(message, repeated, tag = "1")]
    pub primary: ::prost::alloc::vec::Vec<WorkPlace>,
    #[prost(message, repeated, tag = "2")]
    pub additional: ::prost::alloc::vec::Vec<WorkPlace>,
}
/// Specialty structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Specialty {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub specialty_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub medical_school: ::prost::alloc::string::String,
}
/// Education structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Education {
    #[prost(string, tag = "1")]
    pub license_number: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub medical_school: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub specialties: ::prost::alloc::vec::Vec<Specialty>,
    #[prost(message, repeated, tag = "4")]
    pub additional_specialties: ::prost::alloc::vec::Vec<Specialty>,
    #[prost(string, repeated, tag = "5")]
    pub special_interests: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Documents structure
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Documents {
    #[prost(string, tag = "1")]
    pub profile_image_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id_card_image_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub book_bank_image_url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub med_license_image_url: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub certificate_image_urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Main OnBoardingInfo message
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OnBoardingInfo {
    #[prost(enumeration = "super::common::ConsultationChannel", tag = "1")]
    pub profession: i32,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<OnBoardingStatus>,
    #[prost(string, tag = "3")]
    pub academic_position: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub citizen_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub name: ::core::option::Option<super::common::LocalizedString>,
    #[prost(message, optional, tag = "6")]
    pub address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "7")]
    pub work_place: ::core::option::Option<SelectedWorkPlace>,
    #[prost(message, optional, tag = "8")]
    pub education: ::core::option::Option<Education>,
    #[prost(message, optional, tag = "9")]
    pub documents: ::core::option::Option<Documents>,
}
