// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "notification/notification.proto" (package "tdh.protocol.notification", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Notification payload sent via Pub/Sub
 *
 * @generated from protobuf message tdh.protocol.notification.NotificationPayload
 */
export interface NotificationPayload {
    /**
     * @generated from protobuf field: tdh.protocol.notification.NotificationType type = 1
     */
    type: NotificationType;
    /**
     * @generated from protobuf field: repeated int32 doctor_account_ids = 2
     */
    doctorAccountIds: number[];
    /**
     * @generated from protobuf field: string title = 3
     */
    title: string;
    /**
     * @generated from protobuf field: string body = 4
     */
    body: string;
    /**
     * @generated from protobuf field: map<string, string> data = 5
     */
    data: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: string category = 6
     */
    category: string;
    /**
     * @generated from protobuf field: int64 scheduled_at = 7
     */
    scheduledAt: bigint; // Unix timestamp
}
/**
 * Payload for Cloud Tasks execution
 *
 * @generated from protobuf message tdh.protocol.notification.ScheduledNotificationTask
 */
export interface ScheduledNotificationTask {
    /**
     * @generated from protobuf field: tdh.protocol.notification.NotificationPayload notification = 1
     */
    notification?: NotificationPayload;
    /**
     * @generated from protobuf field: int64 original_schedule_time = 2
     */
    originalScheduleTime: bigint;
    /**
     * @generated from protobuf field: uint32 chain_count = 3
     */
    chainCount: number;
}
/**
 * Pub/Sub push message wrapper
 *
 * @generated from protobuf message tdh.protocol.notification.PubsubPushMessage
 */
export interface PubsubPushMessage {
    /**
     * @generated from protobuf field: tdh.protocol.notification.PubsubMessage message = 1
     */
    message?: PubsubMessage;
    /**
     * @generated from protobuf field: string subscription = 2
     */
    subscription: string;
}
/**
 * Individual Pub/Sub message
 *
 * @generated from protobuf message tdh.protocol.notification.PubsubMessage
 */
export interface PubsubMessage {
    /**
     * @generated from protobuf field: string data = 1
     */
    data: string; // Base64-encoded
    /**
     * @generated from protobuf field: string message_id = 2
     */
    messageId: string;
    /**
     * @generated from protobuf field: int64 publish_time = 3
     */
    publishTime: bigint;
    /**
     * @generated from protobuf field: map<string, string> attributes = 4
     */
    attributes: {
        [key: string]: string;
    };
}
/**
 * Notification types
 *
 * @generated from protobuf enum tdh.protocol.notification.NotificationType
 */
export enum NotificationType {
    /**
     * @generated from protobuf enum value: NOTIFICATION_TYPE_UNSPECIFIED = 0;
     */
    NOTIFICATION_TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: APPOINTMENT = 1;
     */
    APPOINTMENT = 1,
    /**
     * @generated from protobuf enum value: CONSULTATION = 2;
     */
    CONSULTATION = 2,
    /**
     * @generated from protobuf enum value: SYSTEM = 3;
     */
    SYSTEM = 3,
    /**
     * @generated from protobuf enum value: BROADCAST = 4;
     */
    BROADCAST = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class NotificationPayload$Type extends MessageType<NotificationPayload> {
    constructor() {
        super("tdh.protocol.notification.NotificationPayload", [
            { no: 1, name: "type", kind: "enum", T: () => ["tdh.protocol.notification.NotificationType", NotificationType] },
            { no: 2, name: "doctor_account_ids", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "body", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "data", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 6, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "scheduled_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<NotificationPayload>): NotificationPayload {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.doctorAccountIds = [];
        message.title = "";
        message.body = "";
        message.data = {};
        message.category = "";
        message.scheduledAt = 0n;
        if (value !== undefined)
            reflectionMergePartial<NotificationPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotificationPayload): NotificationPayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* tdh.protocol.notification.NotificationType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* repeated int32 doctor_account_ids */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.doctorAccountIds.push(reader.int32());
                    else
                        message.doctorAccountIds.push(reader.int32());
                    break;
                case /* string title */ 3:
                    message.title = reader.string();
                    break;
                case /* string body */ 4:
                    message.body = reader.string();
                    break;
                case /* map<string, string> data */ 5:
                    this.binaryReadMap5(message.data, reader, options);
                    break;
                case /* string category */ 6:
                    message.category = reader.string();
                    break;
                case /* int64 scheduled_at */ 7:
                    message.scheduledAt = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap5(map: NotificationPayload["data"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof NotificationPayload["data"] | undefined, val: NotificationPayload["data"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for tdh.protocol.notification.NotificationPayload.data");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: NotificationPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* tdh.protocol.notification.NotificationType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* repeated int32 doctor_account_ids = 2; */
        if (message.doctorAccountIds.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.doctorAccountIds.length; i++)
                writer.int32(message.doctorAccountIds[i]);
            writer.join();
        }
        /* string title = 3; */
        if (message.title !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.title);
        /* string body = 4; */
        if (message.body !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.body);
        /* map<string, string> data = 5; */
        for (let k of globalThis.Object.keys(message.data))
            writer.tag(5, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.data[k]).join();
        /* string category = 6; */
        if (message.category !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.category);
        /* int64 scheduled_at = 7; */
        if (message.scheduledAt !== 0n)
            writer.tag(7, WireType.Varint).int64(message.scheduledAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.notification.NotificationPayload
 */
export const NotificationPayload = new NotificationPayload$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScheduledNotificationTask$Type extends MessageType<ScheduledNotificationTask> {
    constructor() {
        super("tdh.protocol.notification.ScheduledNotificationTask", [
            { no: 1, name: "notification", kind: "message", T: () => NotificationPayload },
            { no: 2, name: "original_schedule_time", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "chain_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ScheduledNotificationTask>): ScheduledNotificationTask {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.originalScheduleTime = 0n;
        message.chainCount = 0;
        if (value !== undefined)
            reflectionMergePartial<ScheduledNotificationTask>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScheduledNotificationTask): ScheduledNotificationTask {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* tdh.protocol.notification.NotificationPayload notification */ 1:
                    message.notification = NotificationPayload.internalBinaryRead(reader, reader.uint32(), options, message.notification);
                    break;
                case /* int64 original_schedule_time */ 2:
                    message.originalScheduleTime = reader.int64().toBigInt();
                    break;
                case /* uint32 chain_count */ 3:
                    message.chainCount = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScheduledNotificationTask, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* tdh.protocol.notification.NotificationPayload notification = 1; */
        if (message.notification)
            NotificationPayload.internalBinaryWrite(message.notification, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int64 original_schedule_time = 2; */
        if (message.originalScheduleTime !== 0n)
            writer.tag(2, WireType.Varint).int64(message.originalScheduleTime);
        /* uint32 chain_count = 3; */
        if (message.chainCount !== 0)
            writer.tag(3, WireType.Varint).uint32(message.chainCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.notification.ScheduledNotificationTask
 */
export const ScheduledNotificationTask = new ScheduledNotificationTask$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PubsubPushMessage$Type extends MessageType<PubsubPushMessage> {
    constructor() {
        super("tdh.protocol.notification.PubsubPushMessage", [
            { no: 1, name: "message", kind: "message", T: () => PubsubMessage },
            { no: 2, name: "subscription", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PubsubPushMessage>): PubsubPushMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.subscription = "";
        if (value !== undefined)
            reflectionMergePartial<PubsubPushMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PubsubPushMessage): PubsubPushMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* tdh.protocol.notification.PubsubMessage message */ 1:
                    message.message = PubsubMessage.internalBinaryRead(reader, reader.uint32(), options, message.message);
                    break;
                case /* string subscription */ 2:
                    message.subscription = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PubsubPushMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* tdh.protocol.notification.PubsubMessage message = 1; */
        if (message.message)
            PubsubMessage.internalBinaryWrite(message.message, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string subscription = 2; */
        if (message.subscription !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.subscription);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.notification.PubsubPushMessage
 */
export const PubsubPushMessage = new PubsubPushMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PubsubMessage$Type extends MessageType<PubsubMessage> {
    constructor() {
        super("tdh.protocol.notification.PubsubMessage", [
            { no: 1, name: "data", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "publish_time", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "attributes", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<PubsubMessage>): PubsubMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = "";
        message.messageId = "";
        message.publishTime = 0n;
        message.attributes = {};
        if (value !== undefined)
            reflectionMergePartial<PubsubMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PubsubMessage): PubsubMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string data */ 1:
                    message.data = reader.string();
                    break;
                case /* string message_id */ 2:
                    message.messageId = reader.string();
                    break;
                case /* int64 publish_time */ 3:
                    message.publishTime = reader.int64().toBigInt();
                    break;
                case /* map<string, string> attributes */ 4:
                    this.binaryReadMap4(message.attributes, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap4(map: PubsubMessage["attributes"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof PubsubMessage["attributes"] | undefined, val: PubsubMessage["attributes"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for tdh.protocol.notification.PubsubMessage.attributes");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: PubsubMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string data = 1; */
        if (message.data !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.data);
        /* string message_id = 2; */
        if (message.messageId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.messageId);
        /* int64 publish_time = 3; */
        if (message.publishTime !== 0n)
            writer.tag(3, WireType.Varint).int64(message.publishTime);
        /* map<string, string> attributes = 4; */
        for (let k of globalThis.Object.keys(message.attributes))
            writer.tag(4, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.attributes[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.notification.PubsubMessage
 */
export const PubsubMessage = new PubsubMessage$Type();
