// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "onboarding/doctor.proto" (package "tdh.protocol.onboarding", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { LocalizedString } from "../common/localization";
import { ConsultationChannel } from "../common/consulting";
/**
 * OnBoardingStatus - discriminated union with variant-specific data
 *
 * @generated from protobuf message tdh.protocol.onboarding.OnBoardingStatus
 */
export interface OnBoardingStatus {
    /**
     * @generated from protobuf oneof: status
     */
    status: {
        oneofKind: "draft";
        /**
         * @generated from protobuf field: tdh.protocol.onboarding.Draft draft = 1
         */
        draft: Draft;
    } | {
        oneofKind: "pendingApproval";
        /**
         * @generated from protobuf field: tdh.protocol.onboarding.PendingApproval pending_approval = 2
         */
        pendingApproval: PendingApproval;
    } | {
        oneofKind: "cancelledByUser";
        /**
         * @generated from protobuf field: tdh.protocol.onboarding.CancelledByUser cancelled_by_user = 3
         */
        cancelledByUser: CancelledByUser;
    } | {
        oneofKind: "approved";
        /**
         * @generated from protobuf field: tdh.protocol.onboarding.Approved approved = 4
         */
        approved: Approved;
    } | {
        oneofKind: "rejected";
        /**
         * @generated from protobuf field: tdh.protocol.onboarding.Rejected rejected = 5
         */
        rejected: Rejected;
    } | {
        oneofKind: "deactivated";
        /**
         * @generated from protobuf field: tdh.protocol.onboarding.Deactivated deactivated = 6
         */
        deactivated: Deactivated;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message tdh.protocol.onboarding.Draft
 */
export interface Draft {
}
/**
 * @generated from protobuf message tdh.protocol.onboarding.PendingApproval
 */
export interface PendingApproval {
}
/**
 * @generated from protobuf message tdh.protocol.onboarding.CancelledByUser
 */
export interface CancelledByUser {
}
/**
 * @generated from protobuf message tdh.protocol.onboarding.Approved
 */
export interface Approved {
}
/**
 * @generated from protobuf message tdh.protocol.onboarding.Rejected
 */
export interface Rejected {
    /**
     * @generated from protobuf field: string reason = 1
     */
    reason: string;
}
/**
 * @generated from protobuf message tdh.protocol.onboarding.Deactivated
 */
export interface Deactivated {
    /**
     * @generated from protobuf field: string reason = 1
     */
    reason: string;
}
/**
 * Name structure
 *
 * @generated from protobuf message tdh.protocol.onboarding.Name
 */
export interface Name {
    /**
     * @generated from protobuf field: string firstname = 1
     */
    firstname: string;
    /**
     * @generated from protobuf field: string lastname = 2
     */
    lastname: string;
}
/**
 * Address structure
 *
 * @generated from protobuf message tdh.protocol.onboarding.Address
 */
export interface Address {
    /**
     * @generated from protobuf field: string address_detail = 1
     */
    addressDetail: string;
    /**
     * @generated from protobuf field: string sub_district = 2
     */
    subDistrict: string;
    /**
     * @generated from protobuf field: string district = 3
     */
    district: string;
    /**
     * @generated from protobuf field: string province = 4
     */
    province: string;
    /**
     * @generated from protobuf field: string postal_code = 5
     */
    postalCode: string;
}
/**
 * Work place structure
 *
 * @generated from protobuf message tdh.protocol.onboarding.WorkPlace
 */
export interface WorkPlace {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
}
/**
 * @generated from protobuf message tdh.protocol.onboarding.SelectedWorkPlace
 */
export interface SelectedWorkPlace {
    /**
     * @generated from protobuf field: repeated tdh.protocol.onboarding.WorkPlace primary = 1
     */
    primary: WorkPlace[];
    /**
     * @generated from protobuf field: repeated tdh.protocol.onboarding.WorkPlace additional = 2
     */
    additional: WorkPlace[];
}
/**
 * Specialty structure
 *
 * @generated from protobuf message tdh.protocol.onboarding.Specialty
 */
export interface Specialty {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string specialty_type = 3
     */
    specialtyType: string;
    /**
     * @generated from protobuf field: string medical_school = 4
     */
    medicalSchool: string;
}
/**
 * Education structure
 *
 * @generated from protobuf message tdh.protocol.onboarding.Education
 */
export interface Education {
    /**
     * @generated from protobuf field: string license_number = 1
     */
    licenseNumber: string;
    /**
     * @generated from protobuf field: string medical_school = 2
     */
    medicalSchool: string;
    /**
     * @generated from protobuf field: repeated tdh.protocol.onboarding.Specialty specialties = 3
     */
    specialties: Specialty[];
    /**
     * @generated from protobuf field: repeated tdh.protocol.onboarding.Specialty additional_specialties = 4
     */
    additionalSpecialties: Specialty[];
    /**
     * @generated from protobuf field: repeated string special_interests = 5
     */
    specialInterests: string[];
}
/**
 * Documents structure
 *
 * @generated from protobuf message tdh.protocol.onboarding.Documents
 */
export interface Documents {
    /**
     * @generated from protobuf field: string profile_image_url = 1
     */
    profileImageUrl: string;
    /**
     * @generated from protobuf field: string id_card_image_url = 2
     */
    idCardImageUrl: string;
    /**
     * @generated from protobuf field: string book_bank_image_url = 3
     */
    bookBankImageUrl: string;
    /**
     * @generated from protobuf field: string med_license_image_url = 4
     */
    medLicenseImageUrl: string;
    /**
     * @generated from protobuf field: repeated string certificate_image_urls = 5
     */
    certificateImageUrls: string[];
}
/**
 * Main OnBoardingInfo message
 *
 * @generated from protobuf message tdh.protocol.onboarding.OnBoardingInfo
 */
export interface OnBoardingInfo {
    /**
     * @generated from protobuf field: tdh.protocol.common.ConsultationChannel profession = 1
     */
    profession: ConsultationChannel;
    /**
     * @generated from protobuf field: tdh.protocol.onboarding.OnBoardingStatus status = 2
     */
    status?: OnBoardingStatus;
    /**
     * @generated from protobuf field: string academic_position = 3
     */
    academicPosition: string;
    /**
     * @generated from protobuf field: string citizen_id = 4
     */
    citizenId: string;
    /**
     * @generated from protobuf field: tdh.protocol.common.LocalizedString name = 5
     */
    name?: LocalizedString;
    /**
     * @generated from protobuf field: tdh.protocol.onboarding.Address address = 6
     */
    address?: Address;
    /**
     * @generated from protobuf field: tdh.protocol.onboarding.SelectedWorkPlace work_place = 7
     */
    workPlace?: SelectedWorkPlace;
    /**
     * @generated from protobuf field: tdh.protocol.onboarding.Education education = 8
     */
    education?: Education;
    /**
     * @generated from protobuf field: tdh.protocol.onboarding.Documents documents = 9
     */
    documents?: Documents;
}
// @generated message type with reflection information, may provide speed optimized methods
class OnBoardingStatus$Type extends MessageType<OnBoardingStatus> {
    constructor() {
        super("tdh.protocol.onboarding.OnBoardingStatus", [
            { no: 1, name: "draft", kind: "message", oneof: "status", T: () => Draft },
            { no: 2, name: "pending_approval", kind: "message", oneof: "status", T: () => PendingApproval },
            { no: 3, name: "cancelled_by_user", kind: "message", oneof: "status", T: () => CancelledByUser },
            { no: 4, name: "approved", kind: "message", oneof: "status", T: () => Approved },
            { no: 5, name: "rejected", kind: "message", oneof: "status", T: () => Rejected },
            { no: 6, name: "deactivated", kind: "message", oneof: "status", T: () => Deactivated }
        ]);
    }
    create(value?: PartialMessage<OnBoardingStatus>): OnBoardingStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<OnBoardingStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OnBoardingStatus): OnBoardingStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* tdh.protocol.onboarding.Draft draft */ 1:
                    message.status = {
                        oneofKind: "draft",
                        draft: Draft.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).draft)
                    };
                    break;
                case /* tdh.protocol.onboarding.PendingApproval pending_approval */ 2:
                    message.status = {
                        oneofKind: "pendingApproval",
                        pendingApproval: PendingApproval.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).pendingApproval)
                    };
                    break;
                case /* tdh.protocol.onboarding.CancelledByUser cancelled_by_user */ 3:
                    message.status = {
                        oneofKind: "cancelledByUser",
                        cancelledByUser: CancelledByUser.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).cancelledByUser)
                    };
                    break;
                case /* tdh.protocol.onboarding.Approved approved */ 4:
                    message.status = {
                        oneofKind: "approved",
                        approved: Approved.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).approved)
                    };
                    break;
                case /* tdh.protocol.onboarding.Rejected rejected */ 5:
                    message.status = {
                        oneofKind: "rejected",
                        rejected: Rejected.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).rejected)
                    };
                    break;
                case /* tdh.protocol.onboarding.Deactivated deactivated */ 6:
                    message.status = {
                        oneofKind: "deactivated",
                        deactivated: Deactivated.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).deactivated)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OnBoardingStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* tdh.protocol.onboarding.Draft draft = 1; */
        if (message.status.oneofKind === "draft")
            Draft.internalBinaryWrite(message.status.draft, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.PendingApproval pending_approval = 2; */
        if (message.status.oneofKind === "pendingApproval")
            PendingApproval.internalBinaryWrite(message.status.pendingApproval, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.CancelledByUser cancelled_by_user = 3; */
        if (message.status.oneofKind === "cancelledByUser")
            CancelledByUser.internalBinaryWrite(message.status.cancelledByUser, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.Approved approved = 4; */
        if (message.status.oneofKind === "approved")
            Approved.internalBinaryWrite(message.status.approved, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.Rejected rejected = 5; */
        if (message.status.oneofKind === "rejected")
            Rejected.internalBinaryWrite(message.status.rejected, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.Deactivated deactivated = 6; */
        if (message.status.oneofKind === "deactivated")
            Deactivated.internalBinaryWrite(message.status.deactivated, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.OnBoardingStatus
 */
export const OnBoardingStatus = new OnBoardingStatus$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Draft$Type extends MessageType<Draft> {
    constructor() {
        super("tdh.protocol.onboarding.Draft", []);
    }
    create(value?: PartialMessage<Draft>): Draft {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Draft>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Draft): Draft {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Draft, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Draft
 */
export const Draft = new Draft$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PendingApproval$Type extends MessageType<PendingApproval> {
    constructor() {
        super("tdh.protocol.onboarding.PendingApproval", []);
    }
    create(value?: PartialMessage<PendingApproval>): PendingApproval {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PendingApproval>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PendingApproval): PendingApproval {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PendingApproval, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.PendingApproval
 */
export const PendingApproval = new PendingApproval$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelledByUser$Type extends MessageType<CancelledByUser> {
    constructor() {
        super("tdh.protocol.onboarding.CancelledByUser", []);
    }
    create(value?: PartialMessage<CancelledByUser>): CancelledByUser {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CancelledByUser>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelledByUser): CancelledByUser {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelledByUser, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.CancelledByUser
 */
export const CancelledByUser = new CancelledByUser$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Approved$Type extends MessageType<Approved> {
    constructor() {
        super("tdh.protocol.onboarding.Approved", []);
    }
    create(value?: PartialMessage<Approved>): Approved {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Approved>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Approved): Approved {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Approved, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Approved
 */
export const Approved = new Approved$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Rejected$Type extends MessageType<Rejected> {
    constructor() {
        super("tdh.protocol.onboarding.Rejected", [
            { no: 1, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Rejected>): Rejected {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reason = "";
        if (value !== undefined)
            reflectionMergePartial<Rejected>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Rejected): Rejected {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string reason */ 1:
                    message.reason = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Rejected, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string reason = 1; */
        if (message.reason !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.reason);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Rejected
 */
export const Rejected = new Rejected$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Deactivated$Type extends MessageType<Deactivated> {
    constructor() {
        super("tdh.protocol.onboarding.Deactivated", [
            { no: 1, name: "reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Deactivated>): Deactivated {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reason = "";
        if (value !== undefined)
            reflectionMergePartial<Deactivated>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Deactivated): Deactivated {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string reason */ 1:
                    message.reason = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Deactivated, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string reason = 1; */
        if (message.reason !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.reason);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Deactivated
 */
export const Deactivated = new Deactivated$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Name$Type extends MessageType<Name> {
    constructor() {
        super("tdh.protocol.onboarding.Name", [
            { no: 1, name: "firstname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "lastname", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Name>): Name {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.firstname = "";
        message.lastname = "";
        if (value !== undefined)
            reflectionMergePartial<Name>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Name): Name {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string firstname */ 1:
                    message.firstname = reader.string();
                    break;
                case /* string lastname */ 2:
                    message.lastname = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Name, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string firstname = 1; */
        if (message.firstname !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.firstname);
        /* string lastname = 2; */
        if (message.lastname !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.lastname);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Name
 */
export const Name = new Name$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Address$Type extends MessageType<Address> {
    constructor() {
        super("tdh.protocol.onboarding.Address", [
            { no: 1, name: "address_detail", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sub_district", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "district", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "province", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "postal_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Address>): Address {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.addressDetail = "";
        message.subDistrict = "";
        message.district = "";
        message.province = "";
        message.postalCode = "";
        if (value !== undefined)
            reflectionMergePartial<Address>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Address): Address {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string address_detail */ 1:
                    message.addressDetail = reader.string();
                    break;
                case /* string sub_district */ 2:
                    message.subDistrict = reader.string();
                    break;
                case /* string district */ 3:
                    message.district = reader.string();
                    break;
                case /* string province */ 4:
                    message.province = reader.string();
                    break;
                case /* string postal_code */ 5:
                    message.postalCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Address, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string address_detail = 1; */
        if (message.addressDetail !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.addressDetail);
        /* string sub_district = 2; */
        if (message.subDistrict !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.subDistrict);
        /* string district = 3; */
        if (message.district !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.district);
        /* string province = 4; */
        if (message.province !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.province);
        /* string postal_code = 5; */
        if (message.postalCode !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.postalCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Address
 */
export const Address = new Address$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WorkPlace$Type extends MessageType<WorkPlace> {
    constructor() {
        super("tdh.protocol.onboarding.WorkPlace", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WorkPlace>): WorkPlace {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<WorkPlace>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorkPlace): WorkPlace {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WorkPlace, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.WorkPlace
 */
export const WorkPlace = new WorkPlace$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SelectedWorkPlace$Type extends MessageType<SelectedWorkPlace> {
    constructor() {
        super("tdh.protocol.onboarding.SelectedWorkPlace", [
            { no: 1, name: "primary", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WorkPlace },
            { no: 2, name: "additional", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => WorkPlace }
        ]);
    }
    create(value?: PartialMessage<SelectedWorkPlace>): SelectedWorkPlace {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.primary = [];
        message.additional = [];
        if (value !== undefined)
            reflectionMergePartial<SelectedWorkPlace>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SelectedWorkPlace): SelectedWorkPlace {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated tdh.protocol.onboarding.WorkPlace primary */ 1:
                    message.primary.push(WorkPlace.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated tdh.protocol.onboarding.WorkPlace additional */ 2:
                    message.additional.push(WorkPlace.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SelectedWorkPlace, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated tdh.protocol.onboarding.WorkPlace primary = 1; */
        for (let i = 0; i < message.primary.length; i++)
            WorkPlace.internalBinaryWrite(message.primary[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated tdh.protocol.onboarding.WorkPlace additional = 2; */
        for (let i = 0; i < message.additional.length; i++)
            WorkPlace.internalBinaryWrite(message.additional[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.SelectedWorkPlace
 */
export const SelectedWorkPlace = new SelectedWorkPlace$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Specialty$Type extends MessageType<Specialty> {
    constructor() {
        super("tdh.protocol.onboarding.Specialty", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "specialty_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "medical_school", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Specialty>): Specialty {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.specialtyType = "";
        message.medicalSchool = "";
        if (value !== undefined)
            reflectionMergePartial<Specialty>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Specialty): Specialty {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string specialty_type */ 3:
                    message.specialtyType = reader.string();
                    break;
                case /* string medical_school */ 4:
                    message.medicalSchool = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Specialty, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string specialty_type = 3; */
        if (message.specialtyType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.specialtyType);
        /* string medical_school = 4; */
        if (message.medicalSchool !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.medicalSchool);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Specialty
 */
export const Specialty = new Specialty$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Education$Type extends MessageType<Education> {
    constructor() {
        super("tdh.protocol.onboarding.Education", [
            { no: 1, name: "license_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "medical_school", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "specialties", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Specialty },
            { no: 4, name: "additional_specialties", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Specialty },
            { no: 5, name: "special_interests", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Education>): Education {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.licenseNumber = "";
        message.medicalSchool = "";
        message.specialties = [];
        message.additionalSpecialties = [];
        message.specialInterests = [];
        if (value !== undefined)
            reflectionMergePartial<Education>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Education): Education {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string license_number */ 1:
                    message.licenseNumber = reader.string();
                    break;
                case /* string medical_school */ 2:
                    message.medicalSchool = reader.string();
                    break;
                case /* repeated tdh.protocol.onboarding.Specialty specialties */ 3:
                    message.specialties.push(Specialty.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated tdh.protocol.onboarding.Specialty additional_specialties */ 4:
                    message.additionalSpecialties.push(Specialty.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated string special_interests */ 5:
                    message.specialInterests.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Education, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string license_number = 1; */
        if (message.licenseNumber !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.licenseNumber);
        /* string medical_school = 2; */
        if (message.medicalSchool !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.medicalSchool);
        /* repeated tdh.protocol.onboarding.Specialty specialties = 3; */
        for (let i = 0; i < message.specialties.length; i++)
            Specialty.internalBinaryWrite(message.specialties[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated tdh.protocol.onboarding.Specialty additional_specialties = 4; */
        for (let i = 0; i < message.additionalSpecialties.length; i++)
            Specialty.internalBinaryWrite(message.additionalSpecialties[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated string special_interests = 5; */
        for (let i = 0; i < message.specialInterests.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.specialInterests[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Education
 */
export const Education = new Education$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Documents$Type extends MessageType<Documents> {
    constructor() {
        super("tdh.protocol.onboarding.Documents", [
            { no: 1, name: "profile_image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "id_card_image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "book_bank_image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "med_license_image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "certificate_image_urls", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Documents>): Documents {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.profileImageUrl = "";
        message.idCardImageUrl = "";
        message.bookBankImageUrl = "";
        message.medLicenseImageUrl = "";
        message.certificateImageUrls = [];
        if (value !== undefined)
            reflectionMergePartial<Documents>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Documents): Documents {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string profile_image_url */ 1:
                    message.profileImageUrl = reader.string();
                    break;
                case /* string id_card_image_url */ 2:
                    message.idCardImageUrl = reader.string();
                    break;
                case /* string book_bank_image_url */ 3:
                    message.bookBankImageUrl = reader.string();
                    break;
                case /* string med_license_image_url */ 4:
                    message.medLicenseImageUrl = reader.string();
                    break;
                case /* repeated string certificate_image_urls */ 5:
                    message.certificateImageUrls.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Documents, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string profile_image_url = 1; */
        if (message.profileImageUrl !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.profileImageUrl);
        /* string id_card_image_url = 2; */
        if (message.idCardImageUrl !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.idCardImageUrl);
        /* string book_bank_image_url = 3; */
        if (message.bookBankImageUrl !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.bookBankImageUrl);
        /* string med_license_image_url = 4; */
        if (message.medLicenseImageUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.medLicenseImageUrl);
        /* repeated string certificate_image_urls = 5; */
        for (let i = 0; i < message.certificateImageUrls.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.certificateImageUrls[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.Documents
 */
export const Documents = new Documents$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OnBoardingInfo$Type extends MessageType<OnBoardingInfo> {
    constructor() {
        super("tdh.protocol.onboarding.OnBoardingInfo", [
            { no: 1, name: "profession", kind: "enum", T: () => ["tdh.protocol.common.ConsultationChannel", ConsultationChannel] },
            { no: 2, name: "status", kind: "message", T: () => OnBoardingStatus },
            { no: 3, name: "academic_position", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "citizen_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "name", kind: "message", T: () => LocalizedString },
            { no: 6, name: "address", kind: "message", T: () => Address },
            { no: 7, name: "work_place", kind: "message", T: () => SelectedWorkPlace },
            { no: 8, name: "education", kind: "message", T: () => Education },
            { no: 9, name: "documents", kind: "message", T: () => Documents }
        ]);
    }
    create(value?: PartialMessage<OnBoardingInfo>): OnBoardingInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.profession = 0;
        message.academicPosition = "";
        message.citizenId = "";
        if (value !== undefined)
            reflectionMergePartial<OnBoardingInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OnBoardingInfo): OnBoardingInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* tdh.protocol.common.ConsultationChannel profession */ 1:
                    message.profession = reader.int32();
                    break;
                case /* tdh.protocol.onboarding.OnBoardingStatus status */ 2:
                    message.status = OnBoardingStatus.internalBinaryRead(reader, reader.uint32(), options, message.status);
                    break;
                case /* string academic_position */ 3:
                    message.academicPosition = reader.string();
                    break;
                case /* string citizen_id */ 4:
                    message.citizenId = reader.string();
                    break;
                case /* tdh.protocol.common.LocalizedString name */ 5:
                    message.name = LocalizedString.internalBinaryRead(reader, reader.uint32(), options, message.name);
                    break;
                case /* tdh.protocol.onboarding.Address address */ 6:
                    message.address = Address.internalBinaryRead(reader, reader.uint32(), options, message.address);
                    break;
                case /* tdh.protocol.onboarding.SelectedWorkPlace work_place */ 7:
                    message.workPlace = SelectedWorkPlace.internalBinaryRead(reader, reader.uint32(), options, message.workPlace);
                    break;
                case /* tdh.protocol.onboarding.Education education */ 8:
                    message.education = Education.internalBinaryRead(reader, reader.uint32(), options, message.education);
                    break;
                case /* tdh.protocol.onboarding.Documents documents */ 9:
                    message.documents = Documents.internalBinaryRead(reader, reader.uint32(), options, message.documents);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OnBoardingInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* tdh.protocol.common.ConsultationChannel profession = 1; */
        if (message.profession !== 0)
            writer.tag(1, WireType.Varint).int32(message.profession);
        /* tdh.protocol.onboarding.OnBoardingStatus status = 2; */
        if (message.status)
            OnBoardingStatus.internalBinaryWrite(message.status, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string academic_position = 3; */
        if (message.academicPosition !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.academicPosition);
        /* string citizen_id = 4; */
        if (message.citizenId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.citizenId);
        /* tdh.protocol.common.LocalizedString name = 5; */
        if (message.name)
            LocalizedString.internalBinaryWrite(message.name, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.Address address = 6; */
        if (message.address)
            Address.internalBinaryWrite(message.address, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.SelectedWorkPlace work_place = 7; */
        if (message.workPlace)
            SelectedWorkPlace.internalBinaryWrite(message.workPlace, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.Education education = 8; */
        if (message.education)
            Education.internalBinaryWrite(message.education, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.onboarding.Documents documents = 9; */
        if (message.documents)
            Documents.internalBinaryWrite(message.documents, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.onboarding.OnBoardingInfo
 */
export const OnBoardingInfo = new OnBoardingInfo$Type();
