#!/usr/bin/env python3
"""
parse_catalog.py

อ่านไฟล์ catalog-info.yaml (รองรับ multi-doc YAML คั่นด้วย ---)
แล้ว:
  1. ดึง entityRef ของทุก entity ไม่ว่า kind ไหนก็ตาม
     (Component, API, Resource, System, Domain, Group, User, Location, Template, ...)
  2. ตรวจสอบ spec.definition ของ kind: API / kind: System (AsyncAPI) ทุก pattern:
       - $text: ./path/to/file.yaml   -> ตรวจว่าไฟล์มีอยู่จริง
       - $ref: https://...            -> ไม่ validate ไฟล์ (เป็น URL ภายนอก) แต่ log ไว้
       - inline string (literal | )   -> เช็คว่าไม่ว่างเปล่า, เตือนถ้าดูเป็น placeholder
  3. รองรับหลาย catalog-info.yaml ในโปรเจกต์เดียว (ส่ง path มาเป็น argument ได้หลายไฟล์)
  4. Output เป็น JSON เดียว ให้ workflow เอาไปใช้ต่อ (entities, missing_files, warnings)

Usage:
    python3 parse_catalog.py catalog-info.yaml [more-catalog-info.yaml ...]
"""

import sys
import os
import json
import yaml

VALID_KIND_HINT = {
    "component", "api", "resource", "system", "domain",
    "group", "user", "location", "template",
}

def normalize_entity_ref(kind: str, namespace: str, name: str) -> str:
    kind = (kind or "").strip().lower()
    namespace = (namespace or "default").strip().lower()
    name = (name or "").strip().lower()
    return f"{kind}:{namespace}/{name}"


def looks_like_placeholder(text: str) -> bool:
    """เดาว่า inline definition นี้เป็น placeholder ว่างเปล่า ไม่ใช่ spec จริง"""
    if not text or not text.strip():
        return True
    lowered = text.lower()
    hints = ["paths: {}", "generated at runtime", "generated by the service"]
    return any(h in lowered for h in hints)


def extract_definition_info(spec: dict, catalog_file_dir: str):
    """
    คืนค่า dict อธิบาย definition ของ API/AsyncAPI entity:
      { "mode": "text" | "ref" | "inline" | "none",
        "path": "...",        # เฉพาะ mode=text
        "resolved_path": "...",
        "exists": bool,
        "url": "...",         # เฉพาะ mode=ref
        "is_placeholder": bool # เฉพาะ mode=inline
      }
    """
    if not spec or "definition" not in spec:
        return {"mode": "none"}

    definition = spec["definition"]

    # Pattern: $text reference -> ไฟล์แยก
    if isinstance(definition, dict) and "$text" in definition:
        rel_path = definition["$text"]
        resolved = os.path.normpath(os.path.join(catalog_file_dir, rel_path))
        return {
            "mode": "text",
            "path": rel_path,
            "resolved_path": resolved,
            "exists": os.path.isfile(resolved),
        }

    # Pattern: $ref -> URL ภายนอก (บาง Backstage plugin รองรับ)
    if isinstance(definition, dict) and "$ref" in definition:
        return {
            "mode": "ref",
            "url": definition["$ref"],
        }

    # Pattern: inline string (literal block | หรือ string ธรรมดา)
    if isinstance(definition, str):
        return {
            "mode": "inline",
            "is_placeholder": looks_like_placeholder(definition),
            "length": len(definition),
        }

    # ไม่รู้จัก pattern
    return {"mode": "unknown", "raw_type": type(definition).__name__}


def process_file(filepath: str):
    entities = []
    warnings = []
    missing_files = []

    catalog_dir = os.path.dirname(os.path.abspath(filepath))

    with open(filepath, "r", encoding="utf-8") as f:
        try:
            docs = list(yaml.safe_load_all(f))
        except yaml.YAMLError as e:
            warnings.append(f"[{filepath}] YAML parse error: {e}")
            return entities, warnings, missing_files

    for i, doc in enumerate(docs):
        if not doc:
            continue  # เอกสารว่าง (เช่น --- ท้ายไฟล์)

        if "kind" not in doc:
            warnings.append(f"[{filepath}] doc #{i} ไม่มี field 'kind' ข้ามไป")
            continue

        kind = doc.get("kind", "")
        metadata = doc.get("metadata", {}) or {}
        spec = doc.get("spec", {}) or {}

        name = metadata.get("name")
        if not name:
            warnings.append(f"[{filepath}] doc #{i} kind={kind} ไม่มี metadata.name ข้ามไป")
            continue

        namespace = metadata.get("namespace", "default")
        entity_ref = normalize_entity_ref(kind, namespace, name)

        if kind.lower() not in VALID_KIND_HINT:
            warnings.append(
                f"[{filepath}] entity '{entity_ref}' มี kind '{kind}' ที่ไม่ใช่ kind มาตรฐาน "
                f"(อาจเป็น custom kind ก็ได้ ไม่ error แต่เตือนไว้)"
            )

        if not spec.get("owner") and kind.lower() not in ("location", "domain"):
            warnings.append(f"[{filepath}] entity '{entity_ref}' ไม่มี spec.owner")

        entity_record = {
            "kind": kind,
            "name": name,
            "namespace": namespace,
            "entityRef": entity_ref,
            "owner": spec.get("owner"),
            "source_file": filepath,
        }

        # ตรวจ definition เฉพาะ kind ที่มักมี spec (API หลัก ๆ)
        if kind.lower() == "api":
            def_info = extract_definition_info(spec, catalog_dir)
            entity_record["definition"] = def_info

            if def_info.get("mode") == "text" and not def_info.get("exists"):
                missing_files.append({
                    "entityRef": entity_ref,
                    "path": def_info["path"],
                    "resolved_path": def_info["resolved_path"],
                })
            elif def_info.get("mode") == "inline" and def_info.get("is_placeholder"):
                warnings.append(
                    f"entity '{entity_ref}' ใช้ inline definition แบบ placeholder "
                    f"(สเปกจริงน่าจะ generate จาก runtime endpoint ไม่ใช่จากไฟล์นี้)"
                )
            elif def_info.get("mode") == "none":
                warnings.append(f"entity '{entity_ref}' เป็น kind: API แต่ไม่มี spec.definition เลย")

        entities.append(entity_record)

    return entities, warnings, missing_files


def main():
    if len(sys.argv) < 2:
        print("Usage: parse_catalog.py <catalog-info.yaml> [more files...]", file=sys.stderr)
        sys.exit(1)

    all_entities = []
    all_warnings = []
    all_missing = []

    for filepath in sys.argv[1:]:
        if not os.path.isfile(filepath):
            all_warnings.append(f"ไม่พบไฟล์: {filepath}")
            continue
        entities, warnings, missing = process_file(filepath)
        all_entities.extend(entities)
        all_warnings.extend(warnings)
        all_missing.extend(missing)

    result = {
        "entities": all_entities,
        "entity_refs": [e["entityRef"] for e in all_entities],
        "warnings": all_warnings,
        "missing_files": all_missing,
        "has_blocking_errors": len(all_missing) > 0,
    }

    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()