// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "appointment/appointment.proto" (package "tdh.protocol.appointment", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * AppointmentStatusDoc - discriminated union for appointment states
 *
 * @generated from protobuf message tdh.protocol.appointment.AppointmentStatusDoc
 */
export interface AppointmentStatusDoc {
    /**
     * @generated from protobuf oneof: status
     */
    status: {
        oneofKind: "pending";
        /**
         * @generated from protobuf field: tdh.protocol.appointment.Pending pending = 1
         */
        pending: Pending;
    } | {
        oneofKind: "confirmed";
        /**
         * @generated from protobuf field: tdh.protocol.appointment.Confirmed confirmed = 2
         */
        confirmed: Confirmed;
    } | {
        oneofKind: "cancelled";
        /**
         * @generated from protobuf field: tdh.protocol.appointment.Cancelled cancelled = 3
         */
        cancelled: Cancelled;
    } | {
        oneofKind: "completed";
        /**
         * @generated from protobuf field: tdh.protocol.appointment.Completed completed = 4
         */
        completed: Completed;
    } | {
        oneofKind: "noShow";
        /**
         * @generated from protobuf field: tdh.protocol.appointment.NoShow no_show = 5
         */
        noShow: NoShow;
    } | {
        oneofKind: "rescheduled";
        /**
         * @generated from protobuf field: tdh.protocol.appointment.Rescheduled rescheduled = 6
         */
        rescheduled: Rescheduled;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message tdh.protocol.appointment.Pending
 */
export interface Pending {
    /**
     * @generated from protobuf field: int64 created_at = 1
     */
    createdAt: bigint;
}
/**
 * @generated from protobuf message tdh.protocol.appointment.Confirmed
 */
export interface Confirmed {
    /**
     * @generated from protobuf field: int64 confirmed_at = 1
     */
    confirmedAt: bigint;
    /**
     * @generated from protobuf field: int32 payment_module_id = 2
     */
    paymentModuleId: number;
}
/**
 * @generated from protobuf message tdh.protocol.appointment.Cancelled
 */
export interface Cancelled {
    /**
     * @generated from protobuf field: string cancel_code = 1
     */
    cancelCode: string;
    /**
     * @generated from protobuf field: int64 cancelled_at = 2
     */
    cancelledAt: bigint;
    /**
     * @generated from protobuf field: string cancelled_by = 3
     */
    cancelledBy: string; // "patient", "doctor", "system"
}
/**
 * @generated from protobuf message tdh.protocol.appointment.Completed
 */
export interface Completed {
    /**
     * @generated from protobuf field: int64 completed_at = 1
     */
    completedAt: bigint;
    /**
     * @generated from protobuf field: string session_id = 2
     */
    sessionId: string;
}
/**
 * @generated from protobuf message tdh.protocol.appointment.NoShow
 */
export interface NoShow {
    /**
     * @generated from protobuf field: int64 no_show_at = 1
     */
    noShowAt: bigint;
    /**
     * @generated from protobuf field: string no_show_type = 2
     */
    noShowType: string; // "patient", "doctor"
}
/**
 * @generated from protobuf message tdh.protocol.appointment.Rescheduled
 */
export interface Rescheduled {
    /**
     * @generated from protobuf field: int64 rescheduled_at = 1
     */
    rescheduledAt: bigint;
    /**
     * @generated from protobuf field: string new_booking_id = 2
     */
    newBookingId: string;
    /**
     * @generated from protobuf field: string rescheduled_by = 3
     */
    rescheduledBy: string; // "patient", "doctor"
}
// @generated message type with reflection information, may provide speed optimized methods
class AppointmentStatusDoc$Type extends MessageType<AppointmentStatusDoc> {
    constructor() {
        super("tdh.protocol.appointment.AppointmentStatusDoc", [
            { no: 1, name: "pending", kind: "message", oneof: "status", T: () => Pending },
            { no: 2, name: "confirmed", kind: "message", oneof: "status", T: () => Confirmed },
            { no: 3, name: "cancelled", kind: "message", oneof: "status", T: () => Cancelled },
            { no: 4, name: "completed", kind: "message", oneof: "status", T: () => Completed },
            { no: 5, name: "no_show", kind: "message", oneof: "status", T: () => NoShow },
            { no: 6, name: "rescheduled", kind: "message", oneof: "status", T: () => Rescheduled }
        ]);
    }
    create(value?: PartialMessage<AppointmentStatusDoc>): AppointmentStatusDoc {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<AppointmentStatusDoc>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AppointmentStatusDoc): AppointmentStatusDoc {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* tdh.protocol.appointment.Pending pending */ 1:
                    message.status = {
                        oneofKind: "pending",
                        pending: Pending.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).pending)
                    };
                    break;
                case /* tdh.protocol.appointment.Confirmed confirmed */ 2:
                    message.status = {
                        oneofKind: "confirmed",
                        confirmed: Confirmed.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).confirmed)
                    };
                    break;
                case /* tdh.protocol.appointment.Cancelled cancelled */ 3:
                    message.status = {
                        oneofKind: "cancelled",
                        cancelled: Cancelled.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).cancelled)
                    };
                    break;
                case /* tdh.protocol.appointment.Completed completed */ 4:
                    message.status = {
                        oneofKind: "completed",
                        completed: Completed.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).completed)
                    };
                    break;
                case /* tdh.protocol.appointment.NoShow no_show */ 5:
                    message.status = {
                        oneofKind: "noShow",
                        noShow: NoShow.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).noShow)
                    };
                    break;
                case /* tdh.protocol.appointment.Rescheduled rescheduled */ 6:
                    message.status = {
                        oneofKind: "rescheduled",
                        rescheduled: Rescheduled.internalBinaryRead(reader, reader.uint32(), options, (message.status as any).rescheduled)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AppointmentStatusDoc, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* tdh.protocol.appointment.Pending pending = 1; */
        if (message.status.oneofKind === "pending")
            Pending.internalBinaryWrite(message.status.pending, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.appointment.Confirmed confirmed = 2; */
        if (message.status.oneofKind === "confirmed")
            Confirmed.internalBinaryWrite(message.status.confirmed, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.appointment.Cancelled cancelled = 3; */
        if (message.status.oneofKind === "cancelled")
            Cancelled.internalBinaryWrite(message.status.cancelled, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.appointment.Completed completed = 4; */
        if (message.status.oneofKind === "completed")
            Completed.internalBinaryWrite(message.status.completed, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.appointment.NoShow no_show = 5; */
        if (message.status.oneofKind === "noShow")
            NoShow.internalBinaryWrite(message.status.noShow, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* tdh.protocol.appointment.Rescheduled rescheduled = 6; */
        if (message.status.oneofKind === "rescheduled")
            Rescheduled.internalBinaryWrite(message.status.rescheduled, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.appointment.AppointmentStatusDoc
 */
export const AppointmentStatusDoc = new AppointmentStatusDoc$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Pending$Type extends MessageType<Pending> {
    constructor() {
        super("tdh.protocol.appointment.Pending", [
            { no: 1, name: "created_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<Pending>): Pending {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.createdAt = 0n;
        if (value !== undefined)
            reflectionMergePartial<Pending>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Pending): Pending {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 created_at */ 1:
                    message.createdAt = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Pending, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 created_at = 1; */
        if (message.createdAt !== 0n)
            writer.tag(1, WireType.Varint).int64(message.createdAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.appointment.Pending
 */
export const Pending = new Pending$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Confirmed$Type extends MessageType<Confirmed> {
    constructor() {
        super("tdh.protocol.appointment.Confirmed", [
            { no: 1, name: "confirmed_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "payment_module_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Confirmed>): Confirmed {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.confirmedAt = 0n;
        message.paymentModuleId = 0;
        if (value !== undefined)
            reflectionMergePartial<Confirmed>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Confirmed): Confirmed {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 confirmed_at */ 1:
                    message.confirmedAt = reader.int64().toBigInt();
                    break;
                case /* int32 payment_module_id */ 2:
                    message.paymentModuleId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Confirmed, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 confirmed_at = 1; */
        if (message.confirmedAt !== 0n)
            writer.tag(1, WireType.Varint).int64(message.confirmedAt);
        /* int32 payment_module_id = 2; */
        if (message.paymentModuleId !== 0)
            writer.tag(2, WireType.Varint).int32(message.paymentModuleId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.appointment.Confirmed
 */
export const Confirmed = new Confirmed$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Cancelled$Type extends MessageType<Cancelled> {
    constructor() {
        super("tdh.protocol.appointment.Cancelled", [
            { no: 1, name: "cancel_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "cancelled_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "cancelled_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Cancelled>): Cancelled {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cancelCode = "";
        message.cancelledAt = 0n;
        message.cancelledBy = "";
        if (value !== undefined)
            reflectionMergePartial<Cancelled>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Cancelled): Cancelled {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string cancel_code */ 1:
                    message.cancelCode = reader.string();
                    break;
                case /* int64 cancelled_at */ 2:
                    message.cancelledAt = reader.int64().toBigInt();
                    break;
                case /* string cancelled_by */ 3:
                    message.cancelledBy = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Cancelled, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string cancel_code = 1; */
        if (message.cancelCode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.cancelCode);
        /* int64 cancelled_at = 2; */
        if (message.cancelledAt !== 0n)
            writer.tag(2, WireType.Varint).int64(message.cancelledAt);
        /* string cancelled_by = 3; */
        if (message.cancelledBy !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.cancelledBy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.appointment.Cancelled
 */
export const Cancelled = new Cancelled$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Completed$Type extends MessageType<Completed> {
    constructor() {
        super("tdh.protocol.appointment.Completed", [
            { no: 1, name: "completed_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Completed>): Completed {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.completedAt = 0n;
        message.sessionId = "";
        if (value !== undefined)
            reflectionMergePartial<Completed>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Completed): Completed {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 completed_at */ 1:
                    message.completedAt = reader.int64().toBigInt();
                    break;
                case /* string session_id */ 2:
                    message.sessionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Completed, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 completed_at = 1; */
        if (message.completedAt !== 0n)
            writer.tag(1, WireType.Varint).int64(message.completedAt);
        /* string session_id = 2; */
        if (message.sessionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.sessionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.appointment.Completed
 */
export const Completed = new Completed$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NoShow$Type extends MessageType<NoShow> {
    constructor() {
        super("tdh.protocol.appointment.NoShow", [
            { no: 1, name: "no_show_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "no_show_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NoShow>): NoShow {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.noShowAt = 0n;
        message.noShowType = "";
        if (value !== undefined)
            reflectionMergePartial<NoShow>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NoShow): NoShow {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 no_show_at */ 1:
                    message.noShowAt = reader.int64().toBigInt();
                    break;
                case /* string no_show_type */ 2:
                    message.noShowType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NoShow, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 no_show_at = 1; */
        if (message.noShowAt !== 0n)
            writer.tag(1, WireType.Varint).int64(message.noShowAt);
        /* string no_show_type = 2; */
        if (message.noShowType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.noShowType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.appointment.NoShow
 */
export const NoShow = new NoShow$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Rescheduled$Type extends MessageType<Rescheduled> {
    constructor() {
        super("tdh.protocol.appointment.Rescheduled", [
            { no: 1, name: "rescheduled_at", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "new_booking_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "rescheduled_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Rescheduled>): Rescheduled {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rescheduledAt = 0n;
        message.newBookingId = "";
        message.rescheduledBy = "";
        if (value !== undefined)
            reflectionMergePartial<Rescheduled>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Rescheduled): Rescheduled {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 rescheduled_at */ 1:
                    message.rescheduledAt = reader.int64().toBigInt();
                    break;
                case /* string new_booking_id */ 2:
                    message.newBookingId = reader.string();
                    break;
                case /* string rescheduled_by */ 3:
                    message.rescheduledBy = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Rescheduled, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 rescheduled_at = 1; */
        if (message.rescheduledAt !== 0n)
            writer.tag(1, WireType.Varint).int64(message.rescheduledAt);
        /* string new_booking_id = 2; */
        if (message.newBookingId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.newBookingId);
        /* string rescheduled_by = 3; */
        if (message.rescheduledBy !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.rescheduledBy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.appointment.Rescheduled
 */
export const Rescheduled = new Rescheduled$Type();
