#!/bin/sh

SQL_OUT_FILE=$(mktemp)

cat <<EOF >"$SQL_OUT_FILE"
  DO \$\$
  BEGIN
    CREATE ROLE ${DB_ADMIN_USER} WITH LOGIN NOSUPERUSER CREATEDB NOCREATEROLE PASSWORD '$DB_ADMIN_USER_PASS';
  EXCEPTION
      WHEN duplicate_object THEN
        RAISE NOTICE '%, moving to next statement', SQLERRM USING ERRCODE = SQLSTATE;
  END;
  \$\$;
  DO \$\$
  BEGIN
    CREATE ROLE ${DB_SERVICE_RW_USER} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '$DB_SERVICE_RW_USER_PASS';
  EXCEPTION
      WHEN duplicate_object THEN
        RAISE NOTICE '%, moving to next statement', SQLERRM USING ERRCODE = SQLSTATE;
  END;
  \$\$;
  DO \$\$
  BEGIN
    CREATE ROLE ${DB_SERVICE_RO_USER} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '$DB_SERVICE_RO_USER_PASS';
  EXCEPTION
      WHEN duplicate_object THEN
        RAISE NOTICE '%, moving to next statement', SQLERRM USING ERRCODE = SQLSTATE;
  END;
  \$\$;
EOF

run-pgsql-script-as-postgres.sh "$SQL_OUT_FILE"
rm "$SQL_OUT_FILE"
