#!/bin/sh

SQL_OUT_FILE=$(mktemp)

cat <<EOF >"$SQL_OUT_FILE"
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_SERVICE_RW_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to $DB_SERVICE_RW_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO $DB_SERVICE_RW_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES to $DB_SERVICE_RW_USER;

  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA public GRANT SELECT ON TABLES TO $DB_SERVICE_RO_USER;
  ALTER DEFAULT PRIVILEGES FOR ROLE $DB_ADMIN_USER IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES to $DB_SERVICE_RO_USER;

  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_SERVICE_RW_USER;
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DB_SERVICE_RO_USER;
EOF

run-pgsql-script-as-postgres.sh "$SQL_OUT_FILE"
rm "$SQL_OUT_FILE"
