#!/bin/sh

SQL_OUT_FILE=$(mktemp)

cat <<EOF > "$SQL_OUT_FILE"
  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_ADMIN_USER;
  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_SERVICE_RW_USER;
  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_SERVICE_RO_USER;
  GRANT USAGE ON SCHEMA public TO $DB_ADMIN_USER;
  GRANT USAGE ON SCHEMA public TO $DB_SERVICE_RW_USER;
  GRANT USAGE ON SCHEMA public TO $DB_SERVICE_RO_USER;
  GRANT CREATE ON DATABASE $DB_NAME TO $DB_ADMIN_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_SERVICE_RW_USER;
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DB_SERVICE_RO_USER;
EOF

run-pgsql-script-as-postgres.sh "$SQL_OUT_FILE"
rm "$SQL_OUT_FILE"
