// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "common/consulting.proto" (package "tdh.protocol.common", syntax proto3)
// tslint:disable
/**
 * ConsultationChannel - channel type for consultations
 *
 * @generated from protobuf enum tdh.protocol.common.ConsultationChannel
 */
export enum ConsultationChannel {
    /**
     * @generated from protobuf enum value: CONSULTATION_CHANNEL_UNSPECIFIED = 0;
     */
    CONSULTATION_CHANNEL_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: VIDEO = 1;
     */
    VIDEO = 1,
    /**
     * @generated from protobuf enum value: CHAT = 2;
     */
    CHAT = 2,
    /**
     * @generated from protobuf enum value: VOICE = 3;
     */
    VOICE = 3
}
/**
 * BookingType - appointment booking type
 *
 * @generated from protobuf enum tdh.protocol.common.BookingType
 */
export enum BookingType {
    /**
     * @generated from protobuf enum value: BOOKING_TYPE_UNSPECIFIED = 0;
     */
    BOOKING_TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: SCHEDULED = 1;
     */
    SCHEDULED = 1,
    /**
     * @generated from protobuf enum value: INSTANT = 2;
     */
    INSTANT = 2
}
