// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "common/localization.proto" (package "tdh.protocol.common", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Localized - generic wrapper for internationalized strings
 *
 * @generated from protobuf message tdh.protocol.common.LocalizedString
 */
export interface LocalizedString {
    /**
     * @generated from protobuf field: string th = 1
     */
    th: string; // Thai content
    /**
     * @generated from protobuf field: string en = 2
     */
    en: string; // English content
}
/**
 * Localized<T> equivalent for generic types
 *
 * @generated from protobuf message tdh.protocol.common.LocalizedBool
 */
export interface LocalizedBool {
    /**
     * @generated from protobuf field: bool th = 1
     */
    th: boolean;
    /**
     * @generated from protobuf field: bool en = 2
     */
    en: boolean;
}
/**
 * @generated from protobuf message tdh.protocol.common.LocalizedInt32
 */
export interface LocalizedInt32 {
    /**
     * @generated from protobuf field: int32 th = 1
     */
    th: number;
    /**
     * @generated from protobuf field: int32 en = 2
     */
    en: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class LocalizedString$Type extends MessageType<LocalizedString> {
    constructor() {
        super("tdh.protocol.common.LocalizedString", [
            { no: 1, name: "th", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "en", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalizedString>): LocalizedString {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.th = "";
        message.en = "";
        if (value !== undefined)
            reflectionMergePartial<LocalizedString>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalizedString): LocalizedString {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string th */ 1:
                    message.th = reader.string();
                    break;
                case /* string en */ 2:
                    message.en = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalizedString, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string th = 1; */
        if (message.th !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.th);
        /* string en = 2; */
        if (message.en !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.en);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.common.LocalizedString
 */
export const LocalizedString = new LocalizedString$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalizedBool$Type extends MessageType<LocalizedBool> {
    constructor() {
        super("tdh.protocol.common.LocalizedBool", [
            { no: 1, name: "th", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "en", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<LocalizedBool>): LocalizedBool {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.th = false;
        message.en = false;
        if (value !== undefined)
            reflectionMergePartial<LocalizedBool>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalizedBool): LocalizedBool {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool th */ 1:
                    message.th = reader.bool();
                    break;
                case /* bool en */ 2:
                    message.en = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalizedBool, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool th = 1; */
        if (message.th !== false)
            writer.tag(1, WireType.Varint).bool(message.th);
        /* bool en = 2; */
        if (message.en !== false)
            writer.tag(2, WireType.Varint).bool(message.en);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.common.LocalizedBool
 */
export const LocalizedBool = new LocalizedBool$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalizedInt32$Type extends MessageType<LocalizedInt32> {
    constructor() {
        super("tdh.protocol.common.LocalizedInt32", [
            { no: 1, name: "th", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "en", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<LocalizedInt32>): LocalizedInt32 {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.th = 0;
        message.en = 0;
        if (value !== undefined)
            reflectionMergePartial<LocalizedInt32>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalizedInt32): LocalizedInt32 {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 th */ 1:
                    message.th = reader.int32();
                    break;
                case /* int32 en */ 2:
                    message.en = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalizedInt32, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 th = 1; */
        if (message.th !== 0)
            writer.tag(1, WireType.Varint).int32(message.th);
        /* int32 en = 2; */
        if (message.en !== 0)
            writer.tag(2, WireType.Varint).int32(message.en);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.common.LocalizedInt32
 */
export const LocalizedInt32 = new LocalizedInt32$Type();
