// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "common/patient.proto" (package "tdh.protocol.common", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * PatientIdentity - patient identifier information
 *
 * @generated from protobuf message tdh.protocol.common.PatientIdentity
 */
export interface PatientIdentity {
    /**
     * @generated from protobuf field: int32 account_id = 1
     */
    accountId: number;
    /**
     * @generated from protobuf field: int32 user_profile_id = 2
     */
    userProfileId: number;
    /**
     * @generated from protobuf field: int32 tenant_id = 3
     */
    tenantId: number;
    /**
     * @generated from protobuf field: string oidc_user_id = 4
     */
    oidcUserId: string; // Optional field
}
// @generated message type with reflection information, may provide speed optimized methods
class PatientIdentity$Type extends MessageType<PatientIdentity> {
    constructor() {
        super("tdh.protocol.common.PatientIdentity", [
            { no: 1, name: "account_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "user_profile_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "tenant_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "oidc_user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PatientIdentity>): PatientIdentity {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        message.userProfileId = 0;
        message.tenantId = 0;
        message.oidcUserId = "";
        if (value !== undefined)
            reflectionMergePartial<PatientIdentity>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatientIdentity): PatientIdentity {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 account_id */ 1:
                    message.accountId = reader.int32();
                    break;
                case /* int32 user_profile_id */ 2:
                    message.userProfileId = reader.int32();
                    break;
                case /* int32 tenant_id */ 3:
                    message.tenantId = reader.int32();
                    break;
                case /* string oidc_user_id */ 4:
                    message.oidcUserId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatientIdentity, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 account_id = 1; */
        if (message.accountId !== 0)
            writer.tag(1, WireType.Varint).int32(message.accountId);
        /* int32 user_profile_id = 2; */
        if (message.userProfileId !== 0)
            writer.tag(2, WireType.Varint).int32(message.userProfileId);
        /* int32 tenant_id = 3; */
        if (message.tenantId !== 0)
            writer.tag(3, WireType.Varint).int32(message.tenantId);
        /* string oidc_user_id = 4; */
        if (message.oidcUserId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.oidcUserId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.common.PatientIdentity
 */
export const PatientIdentity = new PatientIdentity$Type();
