// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "common/user.proto" (package "tdh.protocol.common", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * UserIdentity - comprehensive user identifier information
 *
 * @generated from protobuf message tdh.protocol.common.UserIdentity
 */
export interface UserIdentity {
    /**
     * @generated from protobuf field: int32 account_id = 1
     */
    accountId: number;
    /**
     * @generated from protobuf field: int32 account_type = 2
     */
    accountType: number;
    /**
     * @generated from protobuf field: int32 user_profile_id = 3
     */
    userProfileId: number;
    /**
     * @generated from protobuf field: int32 user_main_profile_id = 4
     */
    userMainProfileId: number;
    /**
     * @generated from protobuf field: int32 tenant_id = 5
     */
    tenantId: number;
    /**
     * @generated from protobuf field: string oidc_user_id = 6
     */
    oidcUserId: string; // Optional field
    /**
     * @generated from protobuf field: tdh.protocol.common.UserIdentity.LegacyData legacy_data = 7
     */
    legacyData?: UserIdentity_LegacyData; // Optional field - legacy compatibility
}
/**
 * Legacy data for backward compatibility with legacy headers
 *
 * @generated from protobuf message tdh.protocol.common.UserIdentity.LegacyData
 */
export interface UserIdentity_LegacyData {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: int32 uid = 2
     */
    uid: number;
    /**
     * @generated from protobuf field: string client_id = 3
     */
    clientId: string;
    /**
     * @generated from protobuf field: int32 client_int_id = 4
     */
    clientIntId: number;
    /**
     * @generated from protobuf field: string scopes = 5
     */
    scopes: string;
    /**
     * @generated from protobuf field: string role_code = 6
     */
    roleCode: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class UserIdentity$Type extends MessageType<UserIdentity> {
    constructor() {
        super("tdh.protocol.common.UserIdentity", [
            { no: 1, name: "account_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "account_type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "user_profile_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "user_main_profile_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "tenant_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "oidc_user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "legacy_data", kind: "message", T: () => UserIdentity_LegacyData }
        ]);
    }
    create(value?: PartialMessage<UserIdentity>): UserIdentity {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        message.accountType = 0;
        message.userProfileId = 0;
        message.userMainProfileId = 0;
        message.tenantId = 0;
        message.oidcUserId = "";
        if (value !== undefined)
            reflectionMergePartial<UserIdentity>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserIdentity): UserIdentity {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 account_id */ 1:
                    message.accountId = reader.int32();
                    break;
                case /* int32 account_type */ 2:
                    message.accountType = reader.int32();
                    break;
                case /* int32 user_profile_id */ 3:
                    message.userProfileId = reader.int32();
                    break;
                case /* int32 user_main_profile_id */ 4:
                    message.userMainProfileId = reader.int32();
                    break;
                case /* int32 tenant_id */ 5:
                    message.tenantId = reader.int32();
                    break;
                case /* string oidc_user_id */ 6:
                    message.oidcUserId = reader.string();
                    break;
                case /* tdh.protocol.common.UserIdentity.LegacyData legacy_data */ 7:
                    message.legacyData = UserIdentity_LegacyData.internalBinaryRead(reader, reader.uint32(), options, message.legacyData);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserIdentity, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 account_id = 1; */
        if (message.accountId !== 0)
            writer.tag(1, WireType.Varint).int32(message.accountId);
        /* int32 account_type = 2; */
        if (message.accountType !== 0)
            writer.tag(2, WireType.Varint).int32(message.accountType);
        /* int32 user_profile_id = 3; */
        if (message.userProfileId !== 0)
            writer.tag(3, WireType.Varint).int32(message.userProfileId);
        /* int32 user_main_profile_id = 4; */
        if (message.userMainProfileId !== 0)
            writer.tag(4, WireType.Varint).int32(message.userMainProfileId);
        /* int32 tenant_id = 5; */
        if (message.tenantId !== 0)
            writer.tag(5, WireType.Varint).int32(message.tenantId);
        /* string oidc_user_id = 6; */
        if (message.oidcUserId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.oidcUserId);
        /* tdh.protocol.common.UserIdentity.LegacyData legacy_data = 7; */
        if (message.legacyData)
            UserIdentity_LegacyData.internalBinaryWrite(message.legacyData, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.common.UserIdentity
 */
export const UserIdentity = new UserIdentity$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserIdentity_LegacyData$Type extends MessageType<UserIdentity_LegacyData> {
    constructor() {
        super("tdh.protocol.common.UserIdentity.LegacyData", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "uid", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "client_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "client_int_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "scopes", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "role_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UserIdentity_LegacyData>): UserIdentity_LegacyData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.uid = 0;
        message.clientId = "";
        message.clientIntId = 0;
        message.scopes = "";
        message.roleCode = "";
        if (value !== undefined)
            reflectionMergePartial<UserIdentity_LegacyData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserIdentity_LegacyData): UserIdentity_LegacyData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* int32 uid */ 2:
                    message.uid = reader.int32();
                    break;
                case /* string client_id */ 3:
                    message.clientId = reader.string();
                    break;
                case /* int32 client_int_id */ 4:
                    message.clientIntId = reader.int32();
                    break;
                case /* string scopes */ 5:
                    message.scopes = reader.string();
                    break;
                case /* string role_code */ 6:
                    message.roleCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserIdentity_LegacyData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* int32 uid = 2; */
        if (message.uid !== 0)
            writer.tag(2, WireType.Varint).int32(message.uid);
        /* string client_id = 3; */
        if (message.clientId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.clientId);
        /* int32 client_int_id = 4; */
        if (message.clientIntId !== 0)
            writer.tag(4, WireType.Varint).int32(message.clientIntId);
        /* string scopes = 5; */
        if (message.scopes !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.scopes);
        /* string role_code = 6; */
        if (message.roleCode !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.roleCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tdh.protocol.common.UserIdentity.LegacyData
 */
export const UserIdentity_LegacyData = new UserIdentity_LegacyData$Type();
